services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - "8080:80"
    environment:
      API_BASE_URL: ${API_BASE_URL}
      LAREX_URL: ${LAREX_URL}
    image: uniwuezpd/ocr4all-frontend:${IMAGE_TAG:-latest}
