version: "3.9"
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules/
    ports:
      - "3333:3333"
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}
      VITE_LAREX_URL: ${VITE_LAREX_URL}
