FROM node:20-slim
ENV HOST=0.0.0.0

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR /app
COPY package.json ./

RUN yarn
COPY . .

EXPOSE 3333
ENTRYPOINT [ "pnpm", "dev" ]
